# Generated by Django 5.0.2 on 2025-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='api_key',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
