# Generated by Django 5.0.2 on 2025-11-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_agent_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='firmware',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='ports',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='device',
            name='timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='device',
            name='vulnerabilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
